#开发环境

server:
  port: 8080


#freemarker & thymeleaf
spring:
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    template-loader-path: classpath:/views/
  thymeleaf:
    cache: false
    prefix: classpath:/htmls/
  #数据源配置
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.wk.springboot.vo
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true
#pageHelper
pagehelper:
  helper-dialect: mysql

#显示dao 执行sql语句
logging:
  level:
    com:
      wk:
        springboot:
          dao: debug
